services:
  sql:
    container_name: adiante-sql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=4DI4NT3_P4SS"
      - "MSSQL_PID=Developer"
    ports:
      - 1433:1433

  cache:
    container_name: adiante-cache
    image: redis:8.0.3-alpine3.21
    restart: always
    mem_limit: 1024mb
    ports:
      - 6379:6379
